### ISSUE TITLE
"Menu" completion on tab

### ISSUE THREAD

**Issue by jetersen** [nickcox/cd-extras#18]
Feature/Option to allow PSReadLine like "Menu" completion on tab.

`.\c<ctrl+space>`
![image](https://user-images.githubusercontent.com/1661688/46245674-05b43c00-c3f2-11e8-8028-6122a64711d4.png)

**Comment by nickcox** [comment]
Thanks for this. _cd-extras_ should already offer [menu completions](https://github.com/nickcox/cd-extras#navigation-helper-expansions) for its own commands and for `cd`, `pushd` and `ls` by default.

You'd need to set the PSReadline option `Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete` to bind this to tab instead of the default <kbd>Ctrl</kbd>+<kbd>Space</kbd>.

If that's not working then it might be worth checking the value of `$cde.MenuCompletion` on your system.

**Comment by jetersen** [comment]
Cheers for the `Set-PSReadLineKeyHandler` that did the trick
