### ISSUE TITLE
Tab completion for directories gives full path and no quotes

### ISSUE THREAD

**Issue by thorstenkampe** [nickcox/cd-extras#3]
Trying tab completion for a directory gives full path and no quotes. While the former is debatable, the latter is clearly a bug:

cd-extras:
```
[thorsten] > cd dir<TAB>
[thorsten] > cd F:\cygwin\home\thorsten\directory with space[ENTER]
[thorsten] > pwd

Path
----
F:\cygwin\home\thorsten
```
Standard behaviour:
```
[thorsten] > cd dir<TAB>
[thorsten] > cd '.\directory with space'[ENTER]
[directory with space] > pwd

Path
----
F:\cygwin\home\thorsten\directory with space
```

**Comment by nickcox** [comment]
https://www.powershellgallery.com/packages/cd-extras/0.1.0

**Comment by thorstenkampe** [comment]
Please consider reopening this issue. `cd <TAB>` still completes with the full path. Compare
```
[powershell] > cd a<TAB>
[powershell] > cd F:\cygwin\home\thorsten\.config\powershell\ARCHIVE
```
to
```
[powershell] > cd a<TAB>
[powershell] > cd .\ARCHIVE
```
The former will get problematic in a deep directory structure. At least there should be a rationale why `cd` behaves differently to the standard behavior.

**Comment by thorstenkampe** [comment]
Another issue is that completion acts differently depending on whether `AUTOCD` is used:
```
[powershell] > cd a<TAB>
[powershell] > cd F:\cygwin\home\thorsten\.config\powershell\ARCHIVE
```
```
[powershell] > a<TAB>
[powershell] > .\ARCHIVE
```

**Comment by nickcox** [comment]
I've implemented realtive paths in [0.2.0](https://www.powershellgallery.com/packages/cd-extras/0.2.0). Appreciate any feedback on whether it's working as expected.

**Comment by nickcox** [comment]
AUTO_CD completion is a different issue, imo. I'm currently using the [`Register-ArgumentCompleter`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter) mechanism for completion. In order to hook AUTO_CD I would need to use the poorly documented [`TabExpansion2`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/tabexpansion2) hook.

Happy to consider if you think it's important though.

**Comment by thorstenkampe** [comment]
Works like a charm. Tab completion with and without `cd` (for auto_cd) give now the same relative path.
